### ISSUE TITLE
why show this

### ISSUE THREAD

**Issue by Kelier** [ArtVentureX/comfyui-animatediff#10]
![image](https://github.com/ArtVentureX/comfyui-animatediff/assets/16694478/30d07fa7-a4dd-49d1-9c45-c0e6a12217f7)

**Comment by Kelier** [comment]
cfg set range?

**Comment by artventuredev** [comment]
Hi, the latest version with a better implementation should mitigate the grayed/washed out image issue. Please update to the latest version and give it a try.
