### ISSUE TITLE
Apply ControlNet to only with the first frame

### ISSUE THREAD

**Issue by StableInfo** [ArtVentureX/comfyui-animatediff#11]
I believe that AnimateDiff alternates between multiple seeds to generate every frame right? It makes the outputed Gif kinda coherent, what if I want to use Controlnet to control the first image, can we make the UI and animatediff stop using controlnet for the other frames and instead use the previous frames?

**Comment by artventuredev** [comment]
Hello @StableInfo, my apologies for the delayed response. If you're still looking for a solution, you might find this example helpful: https://github.com/ArtVentureX/comfyui-animatediff#animate-with-starting-and-ending-images. It demonstrates how to apply different weights to each latent image in a batch. With minor modifications, it can be tailored to your requirements.
