### ISSUE TITLE
Rampant noise added at each step of sampling when animdiff is in use.

### ISSUE THREAD

**Issue by Ferniclestix** [ArtVentureX/comfyui-animatediff#12]
there are no errors with my install, no smoking gun. but when I add the Animdiff loader into the workflow, my nodes all seem to permanently start adding noise to every sampling step.

this persists after animdiff is unloaded and requires a server restart to fix.

I am fairly sure this is some odd interaction with my comfyUI install because i've had some issues with it and had to delete tensorflow to make the thing run. so it could easily be my fault but... yeah, this is the only issue I have after fixing comfyUI not starting and it mystifies me.
just seems to bork denoising somehow :<

**Comment by artventuredev** [comment]
Hi @Ferniclestix, sorry for my late reply. Please update to the latest version, this issue should be fixed already.

**Comment by Ferniclestix** [comment]
thanks, ill re-download and check it out. :)
