### ISSUE TITLE
Animate between two images

### ISSUE THREAD

**Issue by p0mad** [ArtVentureX/comfyui-animatediff#15]
Hi, is it possible to have two init images to interpolate between them using animediff for comfy?

I saw something similar for A1111 but not for Comfy!

is there a repo to do that?

**Comment by tungnguyensipher** [comment]
Will look into this when I have time.

**Comment by artventuredev** [comment]
@p0mad, my apologies for the delayed response. If you're still seeking a solution, here's an example workflow that might help: https://github.com/ArtVentureX/comfyui-animatediff#animate-with-starting-and-ending-images
