### ISSUE TITLE
Is it possible to upgrade to support SDXL?

### ISSUE THREAD

**Issue by BoosterCore** [ArtVentureX/comfyui-animatediff#17]
Thanks, looking forward to supporting SDXL

**Comment by BoosterCore** [comment]
This is how I use AnimateDIff now, it’s a little complicated
https://youtu.be/CB7e1GeHa40?si=h7IQ3YwOQ6RDrLpV

**Comment by tungnguyensipher** [comment]
I believe this is the only way right now. There is no support for SDXL on the original AnimateDiff repo yet.
