### ISSUE TITLE
It's splitting the animation into 2 seperate scenes

### ISSUE THREAD

**Issue by cherrerajobs** [ArtVentureX/comfyui-animatediff#2]
Any idea if we can fix this issue on this repository directly? The problem seems to come from the original repo: https://github.com/continue-revolution/sd-webui-animatediff/issues/4
![AnimateDiff_00007_](https://github.com/ArtVentureX/comfyui-animatediff/assets/8894763/e6cd53cb-9878-45da-a58a-a15851882386)

Edit: This might just be a memory issue, I was able to get a full scene by lowering the resolution on a 10GB 3080
![AnimateDiff_00013_](https://github.com/ArtVentureX/comfyui-animatediff/assets/8894763/edfd00cc-b6d0-494f-8ae6-0c9dd4f8ec5b)

**Comment by artventuredev** [comment]
It seems that the issue stems from using long prompt/negative_prompt (more than 75 tokens). However, I'm not an expert in SD, so I can't directly fix it on this repository. I'll keep an eye on updates from the original repo and let you know if the issue gets resolved.
