### ISSUE TITLE
support other models

### ISSUE THREAD

**Issue by extra-large-onions** [ArtVentureX/comfyui-animatediff#20]
is support for [community models](https://huggingface.co/manshoety/AD_Stabilized_Motion) and [mm_sd_v15_v2.ckpt ](https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt) expected anytime soon

**Comment by tungnguyensipher** [comment]
New support is just added @extra-large-onions. But the extension also comes new nodes, you need to replace the old nodes with AnimateDiffModuleLoader & AnimateDiffSampler (replace normal KSampler)
