### ISSUE TITLE
GIF split into multiple scenes

### ISSUE THREAD

**Issue by freeAhao** [ArtVentureX/comfyui-animatediff#21]
[Putting a bunch of stuff into the negative prompt helped clear it up for me.](https://www.reddit.com/r/StableDiffusion/comments/15jcqws/anyone_else_having_issues_with_animatediff/)

That's works for me.

Edit: Still happended when using 512x768, but 512x512、512x576、512x640 ... works fine.

**Comment by tungnguyensipher** [comment]
Not only prompt too long but low VRAM also a cause. When set resolution too high there is not enough VRAM to sample all images in the same batch.

**Comment by freeAhao** [comment]
About 4G VRAM left when sampe.

By the way, i find this [Animation & Inbetween frames using Animatediff & Controlnet (Workflow)](https://www.reddit.com/r/StableDiffusion/comments/16f6xjc/animation_inbetween_frames_using_animatediff/) work with automatic1111.It still got split issue,but setting ControlNET weight correctly can fix this.

And finally i got this result.
![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMGtwZ2c1aHNtYWNldzAxenB4ZWdjZDE5d3J1dDZ0dThwNDhlNWV4aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PtgVJoMws4CbxsBZUA/giphy.gif)

![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcmg1aWNjb2w1N2IwdXlkOWthZ2J2MnJpaXBxcWlxYzgwbzRhNjhtYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nSprDX7b3yaEh2eQqf/giphy.gif)

Can this implement in comfyui?

**Comment by tungnguyensipher** [comment]
I'll try to implement this. Since it's already working on A1111 it should be possible.

Btw the post you linked also mentions about 11GB VRAM to generate 16 frames 512x512. I also encounter the same issue when I have another app consuming VRAM while sampling, turn it off to release VRAM then everything back to normal.

**Comment by freeAhao** [comment]
> I'll try to implement this. Since it's already working on A1111 it should be possible.
> 
> Btw the post you linked also mentions about 11GB VRAM to generate 16 frames 512x512. I also encounter the same issue when I have another app consuming VRAM while sampling, turn it off to release VRAM then everything back to normal.

I tryed new version of animate diff sampler node, 512x768 work's great, no split issue, just some color flashing problem. 

I'm looking forward the ways to make the process controllable in comfyui.

Nice work so far, thank you.

**Comment by artventuredev** [comment]
Loved to hear that.

About the splitting issue, can you try disable xformers with `--disable-xformers` to see if splitting issue is resolved?

**Comment by freeAhao** [comment]
> Loved to hear that.
> 
> About the splitting issue, can you try disable xformers with `--disable-xformers` to see if splitting issue is resolved?

Look's like it have to disable xformers make to it work.

That splitting issue nerver happend again even with 768x768, and no color problem.

But  exception raised randomly and more frequently, after that, all sample will stop working until restart ComfyUI.

**Comment by artventuredev** [comment]
Thanks I'll try to reproduce this on my end. But for high resolution sampling, I think it's bet to generate GIF at low resolution then apply latent upscale after that.

**Comment by artventuredev** [comment]
```RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The current implementation of the xformers attention code has a constraint on the size of the first dimension of the input tensor. When used with certain combinations of prompts, LoRAs, and resolutions, the combined dimension can exceed this limit, leading to the error you're experiencing. You could consider either reducing the resolution or disabling xformers as a workaround.

As for the issue that arises when xformers is disabled, I was unable to replicate it on my end. However, I've made some minor adjustments that might address the problem. Please try the latest commit to see if it resolves the issue.
