### ISSUE TITLE
unable to change frame_number

### ISSUE THREAD

**Issue by brumie** [ArtVentureX/comfyui-animatediff#24]
Hi,
I'm unable to change frame number, it was okay last night but latest update are stuck with 16, lower or higher will generate error

` Error while processing rearrange-reduction pattern "(b f) d c -> (b d) f c".
 Input tensor shape: torch.Size([17, 5120, 320]). Additional info: {'f': 16}.
 Shape mismatch, can't divide axis of length 17 in chunks of 16`

any clue?

**Comment by artventuredev** [comment]
@brumie Please try the latest commit, it should be fixed.

**Comment by brumie** [comment]
> @brumie Please try the latest commit, it should be fixed.

thank you, working fine up to 24
up to 32 will generate error
`RuntimeError: The size of tensor a (28) must match the size of tensor b (24) at non-singleton dimension 1`

Overall I could say the latest commit generate a stable output, sweet!!
4060 Ti 8GB
![AnimateDiff_00330_](https://github.com/ArtVentureX/comfyui-animatediff/assets/10722486/a0d461c0-0475-49b4-8b6e-8c823a6d4fab)

**Comment by artventuredev** [comment]
For `frame_length` higher than 24, please use AnimateDiff v2 [mm_sd_v15_v2.ckpt](https://huggingface.co/guoyww/animatediff/blob/main/mm_sd_v15_v2.ckpt) model.

**Comment by brumie** [comment]
@artventuredev got it, perfectly working, thank you!!
