### ISSUE TITLE
[Known Issue] CUDA error: invalid configuration argument when xformers is enabled

### ISSUE THREAD

**Issue by ycc1519202717** [ArtVentureX/comfyui-animatediff#31]
Error occurred when executing AnimateDiffSampler:
CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the
stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

when i use any workflow，this bug appears。
how to debug this?plz

**Comment by ycc1519202717** [comment]
I used two computers run this , with gpu 3090,4090, and both had this problem

**Comment by artventuredev** [comment]
This is a knows issue with xformers, see #29. You should disable xformers with `--disable-xformers` on startup.
