### ISSUE TITLE
import cv fails

### ISSUE THREAD

**Issue by tobias-dv-lnu** [ArtVentureX/comfyui-animatediff#35]
When using the Load Video node and MPEG format the `import cv` fails with an exception.

The cause is that `opencv-python` is missing, this should be installed in the ComfyUI venv. I.e. having a `requirments.txt` would be a good idea - and possibly lazy install if/when needed.

I have fixed this in the code base by modifying the approach from ComfyUI-Manager. If you want me to contribute please let me know how. Otherwise, I could paste the code here and you can incorporate it if you wish.

Thanks for a great addition to ComfyUI!

**Comment by artventuredev** [comment]
Thanks for pointing this out. I have other nodes that require cv2 already so I missed it.
