### ISSUE TITLE
[Request] Support for MotionLoRAs

### ISSUE THREAD

**Issue by syddharth** [ArtVentureX/comfyui-animatediff#36]
Newly released motion lora's here: https://huggingface.co/guoyww/animatediff
Zoom In | Zoom Out | Zoom Pan Left | Zoom Pan Right | Pan Up | Pan Down | Rolling Anti-Clockwise | Rolling Clockwise

**Comment by artventuredev** [comment]
Look interesting, I'll look into this today.

**Comment by artventuredev** [comment]
Hey @syddharth I just added support for motion Lora, you can try it with the latest update: https://github.com/ArtVentureX/comfyui-animatediff#motion-lora-is-now-supported
