### ISSUE TITLE
Python Line

### ISSUE THREAD

**Issue by Edwin-Giovanni** [ArtVentureX/comfyui-animatediff#39]
Hello, I'm trying to find a specific python line in the "animatediff" .py files if it's there at all, the line i'm looking for it's "pipeline.to("cuda")", i am trying to change it to "pipeline.enable_sequential_cpu_offload()" and see if that allows me to work with higher resolutions on my low VRAM GPU, I've managed to make it work without such change but i would like to have a way to implement this or any other way to optimize the VRAM usage, thank you in advance and have a great day!

The GPU im using it's a RX 6600.

**Comment by artventuredev** [comment]
I believe that `pipeline.enable_sequential_cpu_offload` is for `diffusers` pipelines, which `animatediff` is not, at least in this implementation.

**Comment by Edwin-Giovanni** [comment]
So there is no way to optimize or reduce the amount of VRAM the nodes use?

**Comment by artventuredev** [comment]
`AnimateDiff` isn't actually a separate model; the nodes merely append some custom weights to the original model (and some other custom logic). The workflow is essentially the same as sampling with a `batch_size of` 16 (or the number of frames you're using). Therefore, if you've found a way to conduct normal sampling with reduced GPU usage, it should work seamlessly with `AnimateDiff`.
