### ISSUE TITLE
The node is missing and cannot be loaded properly

### ISSUE THREAD

**Issue by Tanglinling** [ArtVentureX/comfyui-animatediff#46]
Cannot import /root/ComfyUI/custom_nodes/comfyui-animatediff module for custom nodes: cannot import name 'calculate_parameters' from 'comfy.utils' (/root/ComfyUI/comfy/utils.py)

**Comment by artventuredev** [comment]
It appears that the newer version of ComfyUI is causing some code disruptions. I'll make the necessary adjustments shortly.

**Comment by artventuredev** [comment]
@Tanglinling Please try the latest commit, this issue should be resolved.

**Comment by NomeJaExiste** [comment]
I'm having tha same issue

**Comment by artventuredev** [comment]
Which environment are you running ComfyUI, are you on the latest commit (both ComfyUI and AnimateDiff)?

**Comment by NomeJaExiste** [comment]
I updated comfyUI and it got fixed, but now I'm using animateDiff evolved

**Comment by artventuredev** [comment]
Got it, I'll close the issue then.
