### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by Squallpka1** [ArtVentureX/comfyui-animatediff#47]
got this error while running simple workflow.

> Error occurred when executing AnimateDiffModuleLoader:
>
>invalid load key, '<'.
>
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in >recursive_execute
>output_data, output_ui = get_output_data(obj, input_data_all)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in >get_output_data
>return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in >map_node_over_list
>results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui->animatediff\animatediff\nodes.py", line 76, in load_motion_module
>motion_module = load_motion_module(model_name)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui->animatediff\animatediff\model_utils.py", line 61, in load_motion_module
>mm_state_dict = load_torch_file(model_path)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 22, in >load_torch_file
>pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site->packages\torch\serialization.py", line 1028, in load
>return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site->packages\torch\serialization.py", line 1246, in _legacy_load
>magic_number = pickle_module.load(f, **pickle_load_args)
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

try to run other workflow to see if ComfyUI is the problem but other can run well.  Already do the update all using manager.

![Capture](https://github.com/ArtVentureX/comfyui-animatediff/assets/52813961/048e9ee3-15e0-48fe-a1b8-748867cdc6ec)

**Comment by artventuredev** [comment]
I suspect that the checkpoint may be corrupted. Could you please verify its integrity? The size should be approximately 1.8GB. Alternatively, you might want to try re-downloading the checkpoint [mm_sd_v15_v2.ckpt](https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt).

**Comment by Squallpka1** [comment]
Its seem that the case. Thank you for your help.
