### ISSUE TITLE
The node is missing and cannot be loaded properly when I install AnimateDiff Evolved(the another t2video)

### ISSUE THREAD

**Issue by downpink** [ArtVentureX/comfyui-animatediff#48]

**Comment by artventuredev** [comment]
I have both versions installed and all nodes are loading correctly. Could you provide some information to aid in debugging?
- Are you using the latest versions of both extensions?
- Have you encountered any error logs in the console?
- Which ComfyUI commit are you currently using? (You can use this command `git rev-parse --verify HEAD`)

<img width="360" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/d5521527-c4ff-4cd8-ba0b-b176a057b8b2">
<img width="360" alt="image" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/70d4982e-1a54-4c7d-9a8a-810abe8baa2e">

**Comment by downpink** [comment]
awesome work！！I installed the latest version，and everything's running nice
