### ISSUE TITLE
where to find the model AnimeLike25D_v11.safetensors?

### ISSUE THREAD

**Issue by lilyzlt** [ArtVentureX/comfyui-animatediff#54]

**Comment by artventuredev** [comment]
It's here: https://huggingface.co/stb/animelike2d/blob/main/animelike25D_animelike25DV11Pruned.safetensors

But you can just use any model you have.

**Comment by lilyzlt** [comment]
> It's here: https://huggingface.co/stb/animelike2d/blob/main/animelike25D_animelike25DV11Pruned.safetensors
> 
> But you can just use any model you have.

thx
