### ISSUE TITLE
The more frames you set, the grayer the result

### ISSUE THREAD

**Issue by sdqq1234** [ArtVentureX/comfyui-animatediff#6]
I use same promts and seed and set different frames  result:

set 4 frames:
![00007-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/8bf347e4-bc9a-4f9b-b376-275a1259240d)

set 8 frames:
![00009-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/fe00047f-1ed2-461a-967f-c5c5c8ed469a)

set 20 frames:
![00011-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/9848b79b-e6b9-45e7-aa35-7630a5326622)

I also tested the webUI plugin and it was the same problem

**Comment by StableInfo** [comment]
Is it because animateDiff stops using the VAE by any chance?
https://github.com/continue-revolution/sd-webui-animatediff/issues/58

**Comment by tungnguyensipher** [comment]
This issue is fixed in the latest update. You can give it a try.
