### ISSUE TITLE
    orig_maximum_batch_area = model_management.maximum_batch_area

### ISSUE THREAD

**Issue by Karakor23** [ArtVentureX/comfyui-animatediff#65]
(animediff) PS C:\Comfyui> python main.py
** ComfyUI start up time: 2023-11-14 00:10:13.444042

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32614 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Comfyui\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\comfyui-animatediff\__init__.py", line 2, in <module>
    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\nodes.py", line 16, in <module>
    from .sampler import AnimateDiffSampler, AnimateDiffSlidingWindowOptions
  File "C:\ComfyUI\custom_nodes\comfyui-animatediff\animatediff\sampler.py", line 57, in <module>
    orig_maximum_batch_area = model_management.maximum_batch_area
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_management' has no attribute 'maximum_batch_area'

Cannot import C:\ComfyUI\custom_nodes\comfyui-animatediff module for custom nodes: module 'comfy.model_management' has no attribute 'maximum_batch_area'
### ComfyUI Revision: 1680 [eb0407e8] | Released on '2023-11-13'
C:\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds (IMPORT FAILED): C:\ComfyUI\custom_nodes\comfyui-animatediff
   0.2 seconds: C:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: C:\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

Been stuck at this part. Uninstalled comfy completely, made new conda env and still this error.

**Comment by Fandy192018** [comment]
I have encountered the same issue. It seemed to work fine before when I didn't use a virtual environment to create the project. However, after installing the project dependencies within the virtual environment, I started experiencing the same problem as you. I'm not sure how to resolve it

**Comment by Fandy192018** [comment]
think running it within the virtual environment might require installing additional dependencies beyond what it demands by itself

**Comment by artventuredev** [comment]
Should be fixed in with the last commit. It's ComfyUI new update that break the code.
