### ISSUE TITLE
Export pictures

### ISSUE THREAD

**Issue by Malapris** [ArtVentureX/comfyui-animatediff#7]
Could it be possible to export pictures before doing the gif ? (or propose another format)
Thanks

**Comment by Malapris** [comment]
nice job anyway !!

**Comment by artventuredev** [comment]
You can just save the images right after the sampler node or pipe them to whatever node that accept images as input.

<img width="673" alt="Screenshot 2023-07-31 at 03 11 55" src="https://github.com/ArtVentureX/comfyui-animatediff/assets/133728487/6bd117fb-53c0-45fe-aa35-7423d78d7035">
